function y=NI2(i,t,h)
y=(((t-i*h).^2)/(2*h^2)).*indicatrice(t,i*h,(i+1)*h)+...
((((t-i*h).*((i+2)*h-t))/(2*h^2))+((t-(i+1)*h).*((i+3)*h-t))/(2*h^2)).*indicatrice(t,(i+1)*h,(i+2)*h)+...
((((i+3)*h-t).^2)/(2*h^2)).*indicatrice(t,(i+2)*h,(i+3)*h);